In [1]:
import torch
import numpy as np
import cv2

from sklearn.model_selection import train_test_split
from sklearn import metrics

In [2]:
print(torch.version)

<module 'torch.version' from '/home/carlos/Apps/Anaconda/lib/python3.9/site-packages/torch/version.py'>


In [3]:
torch.cuda.is_available()

True

In [4]:
some_data = [[1,2],[3,4]]
some_data

[[1, 2], [3, 4]]

In [5]:
type(some_data)

list

In [6]:
np.array(some_data)

array([[1, 2],
       [3, 4]])

In [7]:
np.asanyarray(some_data)

array([[1, 2],
       [3, 4]])

In [8]:
some_data = torch.tensor(some_data)
type(some_data)

torch.Tensor

In [9]:
some_data.dtype

torch.int64

In [10]:
numpy_array = np.random.rand(3,4)
numpy_array

array([[0.37761751, 0.36360775, 0.02171262, 0.50481616],
       [0.40547174, 0.4009333 , 0.54134666, 0.26252327],
       [0.69086551, 0.85119891, 0.18920639, 0.71083664]])

In [11]:
torch.from_numpy(numpy_array)

tensor([[0.3776, 0.3636, 0.0217, 0.5048],
        [0.4055, 0.4009, 0.5413, 0.2625],
        [0.6909, 0.8512, 0.1892, 0.7108]], dtype=torch.float64)

In [12]:
torch.tensor(numpy_array)

tensor([[0.3776, 0.3636, 0.0217, 0.5048],
        [0.4055, 0.4009, 0.5413, 0.2625],
        [0.6909, 0.8512, 0.1892, 0.7108]], dtype=torch.float64)

In [13]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
my_tensor = torch.rand(3, 4)

In [15]:
my_tensor.dtype

torch.float32

In [16]:
my_tensor.device

device(type='cpu')

In [17]:
my_tensor = my_tensor.to("cuda")

In [18]:
my_tensor.device

device(type='cuda', index=0)

In [19]:
my_tensor[:, 1:3]

tensor([[0.5814, 0.8370],
        [0.0328, 0.9197],
        [0.3084, 0.3349]], device='cuda:0')

In [20]:
my_tensor.mul(my_tensor)

tensor([[0.3289, 0.3380, 0.7005, 0.9148],
        [0.9680, 0.0011, 0.8459, 0.3709],
        [0.0030, 0.0951, 0.1121, 0.3312]], device='cuda:0')

In [21]:
my_tensor * my_tensor

tensor([[0.3289, 0.3380, 0.7005, 0.9148],
        [0.9680, 0.0011, 0.8459, 0.3709],
        [0.0030, 0.0951, 0.1121, 0.3312]], device='cuda:0')

In [22]:
my_tensor.matmul(my_tensor.T)

tensor([[2.2822, 1.9356, 1.0411],
        [1.9356, 2.1859, 0.7221],
        [1.0411, 0.7221, 0.5414]], device='cuda:0')

In [23]:
my_tensor @ my_tensor.T

tensor([[2.2822, 1.9356, 1.0411],
        [1.9356, 2.1859, 0.7221],
        [1.0411, 0.7221, 0.5414]], device='cuda:0')

In [24]:
my_tensor.sum(axis=0)

tensor([1.6118, 0.9226, 2.0915, 2.1410], device='cuda:0')

In [25]:
torch.cat([my_tensor,my_tensor], dim=1)

tensor([[0.5735, 0.5814, 0.8370, 0.9564, 0.5735, 0.5814, 0.8370, 0.9564],
        [0.9839, 0.0328, 0.9197, 0.6090, 0.9839, 0.0328, 0.9197, 0.6090],
        [0.0544, 0.3084, 0.3349, 0.5755, 0.0544, 0.3084, 0.3349, 0.5755]],
       device='cuda:0')

In [26]:
torch.nn.functional.softmax(my_tensor, dim=0)

tensor([[0.3223, 0.4275, 0.3715, 0.4185],
        [0.4859, 0.2470, 0.4036, 0.2957],
        [0.1918, 0.3254, 0.2249, 0.2859]], device='cuda:0')

In [27]:
my_tensor.shape

torch.Size([3, 4])

In [28]:
my_tensor.size()

torch.Size([3, 4])

In [29]:
torch.rand(10, 3, 128, 128).size()

torch.Size([10, 3, 128, 128])

In [30]:
my_tensor

tensor([[0.5735, 0.5814, 0.8370, 0.9564],
        [0.9839, 0.0328, 0.9197, 0.6090],
        [0.0544, 0.3084, 0.3349, 0.5755]], device='cuda:0')

In [31]:
my_tensor.clip(0.2, 0.8)

tensor([[0.5735, 0.5814, 0.8000, 0.8000],
        [0.8000, 0.2000, 0.8000, 0.6090],
        [0.2000, 0.3084, 0.3349, 0.5755]], device='cuda:0')

In [32]:
my_tensor.cpu().detach().numpy()

array([[0.57351685, 0.5813738 , 0.8369572 , 0.9564297 ],
       [0.983868  , 0.03284776, 0.9197253 , 0.60904264],
       [0.0543769 , 0.3083967 , 0.33485115, 0.57547873]], dtype=float32)

## 2.Pytorch Autograd

In [33]:
a = torch.tensor([5.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [34]:
a,b

(tensor([5.], requires_grad=True), tensor([6.], requires_grad=True))

In [35]:
y = a**3 - b**2
y

tensor([89.], grad_fn=<SubBackward0>)

In [36]:
print(a.grad)

None


In [37]:
y.backward()

In [38]:
a.grad

tensor([75.])

In [39]:
b.grad

tensor([-12.])

In [40]:
W = torch.randn(10, 1, requires_grad=True)
b = torch.randn( 1, requires_grad=True)

In [41]:
W

tensor([[-2.4361],
        [ 2.4526],
        [ 1.9439],
        [ 1.0785],
        [ 0.9288],
        [ 1.0066],
        [-1.2935],
        [-1.6125],
        [-0.2724],
        [ 0.9737]], requires_grad=True)

In [42]:
x = torch.rand(1, 10)

In [43]:
x

tensor([[0.5260, 0.3626, 0.0596, 0.1182, 0.2988, 0.3038, 0.6477, 0.3512, 0.1387,
         0.6248]])

In [44]:
output = torch.matmul(x, W) + b

In [45]:
loss = 1 - output
loss

tensor([[0.8966]], grad_fn=<RsubBackward1>)

In [46]:
output

tensor([[0.1034]], grad_fn=<AddBackward0>)

In [47]:
loss.backward()

In [48]:
W.grad

tensor([[-0.5260],
        [-0.3626],
        [-0.0596],
        [-0.1182],
        [-0.2988],
        [-0.3038],
        [-0.6477],
        [-0.3512],
        [-0.1387],
        [-0.6248]])

In [49]:
with torch.no_grad():
    W = W - 0.001 * W.grad.data
W

tensor([[-2.4356],
        [ 2.4530],
        [ 1.9439],
        [ 1.0786],
        [ 0.9291],
        [ 1.0069],
        [-1.2928],
        [-1.6121],
        [-0.2722],
        [ 0.9743]])

3. The dataset class in PyTorch
https://www.youtube.com/watch?v=oWq6aVv5mC8

In [50]:
from sklearn.datasets import make_classification

In [51]:
class CustomDataset:
    def __init__(self, data, targets):
        self.data = data
        self.targets = targets
        
    def __len__(self):
        return self.data.shape[0]
    
    def __getitem__(self, idx):
        current_sample = self.data[idx, :]
        current_target = self.targets[idx]
        return {
            "X": torch.tensor(current_sample, dtype=torch.float),
            "y": torch.tensor(current_target, dtype=torch.long),
        }

In [52]:
data, targets = make_classification(n_samples=1000)

In [53]:
data.shape

(1000, 20)

In [54]:
targets.shape

(1000,)

In [55]:
custom_dataset = CustomDataset(data = data, targets=targets)

In [56]:
len(custom_dataset)

1000

In [57]:
custom_dataset[0]['X'].shape

torch.Size([20])

In [58]:
custom_dataset[345]

{'X': tensor([-0.2819, -0.0902, -1.6077,  2.3667,  0.0417, -2.6973, -0.0807, -0.4468,
         -0.5787, -1.2421, -0.3629,  0.9140, -3.1504,  0.0320,  1.8245, -0.9190,
          0.1985, -0.2278, -0.4686, -0.7829]),
 'y': tensor(1)}

In [59]:
for idx in range(len(custom_dataset)):
    print(custom_dataset[idx])
    break

{'X': tensor([ 0.3797,  0.6402,  0.9393,  1.6014,  0.3428,  0.9340, -0.8851,  0.6097,
        -0.7914,  0.6405,  1.8203,  0.7747,  0.4212, -0.8170, -1.6923,  0.2273,
         0.4406,  0.2355, -0.3178,  2.5346]), 'y': tensor(1)}


4. Dataset class for simple NLP problems: https://www.youtube.com/watch?v=BLwvrcaD4GE

In [60]:
# classification/regression problems
class CustomDataset:
    def __init__(self, data, targets, tokenizer):
        self.data = data
        self.targets = targets
        self.tokenizer = tokenizer
        
    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):
        text = self.data[idx]
        targets = self.targets[idx]
        
        input_ids = tokenizer(text)
        
        return {
            "input_ids": torch.tensor(input_ids, dtype=torch.long),
            "target": torch.tensor(target)
        }

In [61]:
class CustomDataset:
    def __init__(self, image_paths, targets, augmentations):
        self.image_paths = image_paths
        self.targets = targets
        self.augmentations = augmentations
        
    def __len__(self):
        return len(self.image_paths)
    
    def __getitem__(self, idx):
        target = self.targets[idx]
        image = cv2.imread(self.image_paths[idx])
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        augmented = self.augmentations(image = image)
        image = augmented['image']
        image = np.transpose(image, (2, 0, 1)).astype(np.float32)
        return{
            "input_ids": torch.tensor(image),
            "target": torch.tensor(target)
        }

## Dataloader in PyTorch: https://www.youtube.com/watch?v=YUMLKPk77iY

In [62]:
class CustomDataset:
    def __init__(self, data, targets):
        self.data = data
        self.targets = targets
        
    def __len__(self):
        return self.data.shape[0]
    
    def __getitem__(self, idx):
        current_sample = self.data[idx, :]
        current_target = self.targets[idx]
        return {
            "X": torch.tensor(current_sample, dtype=torch.float),
            "y": torch.tensor(current_target, dtype=torch.long),
        }

In [63]:
data, targets = make_classification(n_samples=1000)

In [64]:
dataset = CustomDataset(data, targets)

In [65]:
len(dataset)

1000

In [66]:
#?torch.utils.data.DataLoader

In [67]:
train_loader = torch.utils.data.DataLoader(dataset, batch_size=4, num_workers=2)

In [68]:
for data in train_loader:
    print(data['X'].shape)
    print(data['y'].shape)
    break

torch.Size([4, 20])
torch.Size([4])


In [69]:
# for _ in range(10):
#     for data in train_loader:
#         X = data['X']
#         y = data['y']
#         outputs = model(X,y)
#         #loss = 
#         #loss.backwards()

## 7. Linear regression model in PyTorch https://www.youtube.com/watch?v=gB1KAhL6Hvw


In [70]:
class CustomDataset:
    def __init__(self, data, targets):
        self.data = data
        self.targets = targets
        
    def __len__(self):
        return self.data.shape[0]
    
    def __getitem__(self, idx):
        current_sample = self.data[idx, :]
        current_target = self.targets[idx]
        return {
            "X": torch.tensor(current_sample, dtype=torch.float),
            "y": torch.tensor(current_target, dtype=torch.long),
        }

In [71]:
data, targets = make_classification(n_samples=1000)
train_data, test_data, train_targets, test_targets = train_test_split(
        data, targets, stratify=targets)

In [72]:
train_dataset = CustomDataset(train_data, train_targets)
test_dataset = CustomDataset(test_data, test_targets)

In [73]:
train_loader = train_loader = torch.utils.data.DataLoader(
    train_dataset, batch_size=4, num_workers=2
)

test_loader = torch.utils.data.DataLoader(
    test_dataset, batch_size=4, num_workers=2
)

In [74]:
model = lambda x, w, b: torch.matmul(x, w) + b

In [75]:
model

<function __main__.<lambda>(x, w, b)>

In [76]:
train_data.shape

(750, 20)

In [77]:
W = torch.randn(20, 1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
learning_rate = 0.001

In [78]:
outputs = []
labels = []
with torch.no_grad():
    for data in test_loader:
        xtest = data['X']
        ytest = data['y']

        output = model(xtest, W, b)
        labels.append(ytest)
        outputs.append(output)

In [79]:
metrics.roc_auc_score(torch.cat(labels).view(-1), torch.cat(outputs).view(-1))

0.467776

In [80]:
for epoch in range(10):
    epoch_loss = 0
    counter = 0
    for data in train_loader:
        xtrain = data['X']
        ytrain = data['y']
        
#         if W.grad is not None:
#             W.grad_zero_()
        
        output = model(xtrain, W, b)
        loss = torch.mean((ytrain.view(-1) - output.view(-1))**2)
        epoch_loss = epoch_loss + loss.item()
        loss.backward()
        
#         print(W.grad)
        
        with torch.no_grad():
            W = W - learning_rate * W.grad
            b = b - learning_rate * b.grad
            
#         print(W.grad)

        W.requires_grad_(True)
        b.requires_grad_(True)
        counter += 1
    print(epoch, epoch_loss/counter)

0 18.404463373917213
1 8.414006941377165
2 4.05499775351045
3 2.0229967862684677
4 1.0471081791564505
5 0.5711299816463539
6 0.3366385727546158
7 0.2202087213864867
8 0.16200817899996453
9 0.13274002053893785


In [81]:
outputs = []
labels = []
with torch.no_grad():
    for data in test_loader:
        xtest = data['X']
        ytest = data['y']

        output = model(xtest, W, b)
        labels.append(ytest)
        outputs.append(output)

In [82]:
metrics.roc_auc_score(torch.cat(labels).view(-1), torch.cat(outputs).view(-1))

0.9415680000000001

## 8. Training and validation loops in PyTorch https://www.youtube.com/watch?v=r0TlnPUFG5U

In [83]:
def train_one_step(model, data, optimizer):
    optimizer.zero_grad()
    for k, v in data.items():
        data[k] = v.to("cuda")
    loss = model(**data)
    loss.backward()
    optimizer.step()
    return loss

In [84]:
def train_one_epoch(model, data_loader, optimizer, scheduler):
    model.train()
    total_loss = 0
    for batch_index, data in enumerate(data_loader):
        loss = train_one_step(model, data, optimizer)
        scheduler.step()
        total_loss += loss
    return total_loss

In [85]:
def validate_one_step(model, data, optimizer):
    optimizer.zero_grad()
    for k, v in data.items():
        data[k] = v.to("cuda")
    loss = model(**data)
    return loss

In [87]:
def validate_one_epoch(model, data_loader):
    model.eval()
    total_loss = 0
    for batch_index, data in enumerate(data_loader):
        with torch.no_grad():
            loss = train_one_step(model, data)
            scheduler.step()
            total_loss += loss
    return total_loss

## 9. Understanding torch.nn https://www.youtube.com/watch?v=t67ZS14hw1g

### there is a sequence material to study about the another functions

In [103]:
import torch.nn as nn

In [104]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer1 = nn.Linear(128, 32)
        self.layer2 = nn.Linear(32, 16)
        self.layer3 = nn.Linear(16, 1)
        
    def forward(self, features):
        # (32, 128)
        x = self.layer1(features)
        print(x.shape)
        #(32, 32)
        x = self.layer2(x)
        x = self.layer3(x)
        # (32, 1)
        return x

In [105]:
model = Model()
features = torch.rand((2, 128))
#print(features)
model(features)

torch.Size([2, 32])


tensor([[-0.2504],
        [-0.2623]], grad_fn=<AddmmBackward0>)

In [106]:
features.device

device(type='cpu')

In [107]:
features = features.to('cuda')
model = Model()
model.to('cuda')
model(features)

torch.Size([2, 32])


tensor([[-0.0357],
        [ 0.0195]], device='cuda:0', grad_fn=<AddmmBackward0>)

In [108]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.base = nn.Sequential(
            nn.Linear(128, 32),
            nn.Linear(32, 16),
            nn.Linear(16, 1)
        )
        

        
    def forward(self, features):
        x = self.base(features)
        return x

In [109]:
features = features.to('cuda')
model = Model()
model.to('cuda')
model(features)

tensor([[-0.1218],
        [-0.1479]], device='cuda:0', grad_fn=<AddmmBackward0>)